INSERT INTO LOAITK VALUES ('LK00001', N'Admin')
INSERT INTO LOAITK VALUES ('LK00002', N'User')

INSERT INTO THUONGHIEU VALUES (N'Tissot', N'TH00001.jpg')
INSERT INTO THUONGHIEU VALUES (N'Frederique Constant', N'TH00002.jpg')
INSERT INTO THUONGHIEU VALUES (N'Frederique Constant', N'TH00002.jpg')

INSERT INTO LOAISANPHAM VALUES ('LP00001', N'Đồng hồ nam')
INSERT INTO LOAISANPHAM VALUES ('LP00002', N'Đồng hồ nữ')

INSERT INTO SANPHAM VALUES (N'Đồng hồ Tissot T106.417.16.031.00', N'SP00001.jpg', N'SP00001_1.jpg', N'Đồng hồ nam, Dây da, Vỏ Thép không gỉ 316L/Mạ PVD, Kính sapphire, Bảo hành toàn cầu 2 năm', 1, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 3, 'LP00001', 11930000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ Tissot T085.410.22.013.00', N'SP00002.jpg', N'SP00002_1.jpg', N'Đồng hồ nam, Dây da, Thép không gỉ 316L/Mạ PVD, Kính sapphire, Bảo hành toàn cầu 2 năm, ', 1, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 4, 'LP00001', 10980000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ Tissot T063.617.36.037.00', N'SP00003.jpg', N'SP00003_1.jpg', N'Đồng hồ nam, Dây da, Vỏ Thép không gỉ 316L/Mạ PVD, Kính sapphire, Bảo hành toàn cầu 2 năm', 1, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 6, 'LP00001', 14060000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ Frederique Constant FC-282AS5B4', N'SP00004.jpg', N'SP00004_1.jpg', N'Đồng hồ nam, Dây da, Vỏ Thép không gỉ 316L/Mạ PVD, Kính sapphire, Bảo hành toàn cầu 2 năm', 2, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 2, 'LP00001', 27040000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ Tissot T006.408.22.037.00', N'SP00005.jpg', N'SP00005_1.jpg', N'Thiết kế truyền thống và chuẩn mực của nghệ thuật chế tác đồng hồ, Cỗ máy ETA 2824 được modified đem đến trải nghiệm cơ khí tuyệt vời, Dây da thanh lịch kết hợp cùng lớp vỏ thép trắng xám tạo nên tổng thể hài hòa tuyệt đối', 1, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 4, 'LP00001', 36020000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ Tissot T063.907.36.068.00', N'SP00006.jpg', N'SP00006_1.jpg', N'Đồng hồ nam, Dây da, Vỏ Thép không gỉ 316L/Mạ PVD, Kính sapphire, Bảo hành toàn cầu 2 năm', 1, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 7, 'LP00001', 21940000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ CK (Calvin Klein) K6L2M116', N'SP00007.jpg', N'SP00007_1.jpg', N'Đồng hồ nữ, Thép không gỉ 316L/Mạ PVD, Vỏ Thép không gỉ 316L/Mạ PVD, Kính cứng, Bảo hành toàn cầu 2 năm', 3, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 1, 'LP00002', 6820000)
INSERT INTO SANPHAM VALUES (N'Đồng hồ CK (Calvin Klein) K5U2M141', N'SP00008.jpg', N'SP00008_1.jpg', N'Đồng hồ nữ, Dây da, Vỏ Thép không gỉ 316L/Mạ PVD, Kính cứng, Bảo hành toàn cầu 2 năm', 3, N'XWatch Luxury là địa chỉ đầu tiên tại Việt Nam thực hiện chiến dịch Tẩy chay Đồng hồ Fake - Bảo vệ lợi ích người tiêu dùng (xem chi tiết tại https://thamdinhdongho.vn/) . XWatch Luxury được ủy quyền trực tiếp từ các thương hiệu danh tiếng như Tissot, Frederique Constant, Calvin Klein, Ogival. 100% nhập khẩu nguyên chiếc, đầy đủ phụ kiện đi kèm (sổ, hộp, thẻ bảo hành toàn cầu) và giấy chứng nhận hàng chính hãng.', 3, 'LP00002', 7650000)
