//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Domain.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.CHITIETKMs = new HashSet<CHITIETKM>();
        }
    
        public string MAKM { get; set; }
        public string TENKM { get; set; }
    
        public virtual ICollection<CHITIETKM> CHITIETKMs { get; set; }
    }
}
