<?xml version="1.0" encoding="utf-8"?><Database Name="BANDONGHO" Class="BANDONGHODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-C9BFOB7;Initial Catalog=BANDONGHO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BANDONGHOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDONHANG" Member="CHITIETDONHANGs">
    <Type Name="CHITIETDONHANG">
      <Column Name="MADH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="DONHANG" ThisKey="MADH" OtherKey="MADH" Type="DONHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETDONHANG" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKM" Member="CHITIETKMs">
    <Type Name="CHITIETKM">
      <Column Name="MACTKM" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKM" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="NGAYBATDAUKM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKETTHUCKM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PHANTRAMKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETKM" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETSANPHAM" Member="CHITIETSANPHAMs">
    <Type Name="CHITIETSANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASIZE" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMAU" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAISP" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="LOAISANPHAM_CHITIETSANPHAM" Member="LOAISANPHAM" ThisKey="MALOAISP" OtherKey="MALOAISP" Type="LOAISANPHAM" IsForeignKey="true" />
      <Association Name="MAUSAC_CHITIETSANPHAM" Member="MAUSAC" ThisKey="MAMAU" OtherKey="MAMAU" Type="MAUSAC" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETSANPHAM" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="SIZE_CHITIETSANPHAM" Member="SIZE" ThisKey="MASIZE" OtherKey="MASIZE" Type="SIZE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MADH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DIACHIGIAO" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MADH" OtherKey="MADH" Type="CHITIETDONHANG" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATK" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONHANG" />
      <Association Name="TAIKHOAN_KHACHHANG" Member="TAIKHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MALOAISP" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAISP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MALOAISP" OtherKey="MALOAISP" Type="CHITIETSANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITK" Member="LOAITKs">
    <Type Name="LOAITK">
      <Column Name="MALOAITK" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAITK" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAITK_TAIKHOAN" Member="TAIKHOANs" ThisKey="MALOAITK" OtherKey="MALOAITK" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="CHITIETKMs" ThisKey="MAKM" OtherKey="MAKM" Type="CHITIETKM" />
    </Type>
  </Table>
  <Table Name="dbo.MAUSAC" Member="MAUSACs">
    <Type Name="MAUSAC">
      <Column Name="MAMAU" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMAU" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="MAUSAC_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MAMAU" OtherKey="MAMAU" Type="CHITIETSANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHLON" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="HINHNHO" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="THONGTIN" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MATH" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="DANHGIA" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SANPHAM_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETDONHANG" />
      <Association Name="SANPHAM_CHITIETKM" Member="CHITIETKMs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETKM" />
      <Association Name="SANPHAM_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETSANPHAM" />
      <Association Name="THUONGHIEU_SANPHAM" Member="THUONGHIEU" ThisKey="MATH" OtherKey="MATH" Type="THUONGHIEU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SIZE" Member="SIZEs">
    <Type Name="SIZE">
      <Column Name="MASIZE" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSIZE" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="SIZE_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MASIZE" OtherKey="MASIZE" Type="CHITIETSANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MATK" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="MALOAITK" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Association Name="TAIKHOAN_KHACHHANG" Member="KHACHHANGs" ThisKey="MATK" OtherKey="MATK" Type="KHACHHANG" />
      <Association Name="LOAITK_TAIKHOAN" Member="LOAITK" ThisKey="MALOAITK" OtherKey="MALOAITK" Type="LOAITK" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THUONGHIEU" Member="THUONGHIEUs">
    <Type Name="THUONGHIEU">
      <Column Name="MATH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHTH" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Association Name="THUONGHIEU_SANPHAM" Member="SANPHAMs" ThisKey="MATH" OtherKey="MATH" Type="SANPHAM" />
    </Type>
  </Table>
</Database>